project:
  type: website
  output-dir: docs
  resources: 
    - media/
  render:
    - "output/quarto_content/**/**.qmd"
    - "index.qmd"
format: 
  html:
    html-math-method:
      method: mathjax
      include-in-header: header-includes.html
